@startuml person-full-composition
skinparam ClassAttributeIconSize 0
hide circle

Person *-- DateOfBirth

class Person {
  - name: string
  
  + Person(name: string)
  + print(): void
  + setName(name: string): void
  + getName(): string
}

class DateOfBirth {
  - year: int
  - month: int
  - day: int

  + DateOfBirth(year: int, month: int, day: int)
  + printDateOfBirth(): void
}

@enduml